name: CouponTracker
options:
  bundleIdPrefix: com.coupontracker
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  CouponTracker:
    type: application
    platform: iOS
    sources:
      - path: CouponTracker/Sources
        excludes:
          - "**/.gitkeep"
      - path: CouponTracker/Resources/Assets.xcassets
      - path: CouponTracker/Resources/Data/CardTemplates.json
        buildPhase: resources
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: "CouponTracker"
        PRODUCT_BUNDLE_IDENTIFIER: com.coupontracker.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

  CouponTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CouponTrackerTests
        excludes:
          - "**/.gitkeep"
    dependencies:
      - target: CouponTracker
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/CouponTracker.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/CouponTracker"
